# ftputil.error.PermanentError: 530 Authentication failed.
class AuthError(Exception):
    pass
